use std::{rc::Rc, io::{Result, Error, ErrorKind}};
use xlsx_read::{excel_file::ExcelFile, excel_table::ExcelTable};
use crate::defs::*;

use item_class::ItemClass;
mod item_class;

trait CodeGenerator {
    type Output;
    fn gen_code(&self, end: &'static str, tab_nums: i32) -> Self::Output;
}

enum KeyType {
    None,
    DefKey(Vec<ItemStr>),
    OriginalTemplateId
}

#[derive(Default)]
pub struct DefaultData;

pub struct Parser {
    item_class: ItemClass,
    defaults: DefaultData,
    key_type: KeyType,
}

impl CodeGenerator for Parser {
    type Output = String;

    fn gen_code(&self, end: &'static str, tab_nums: i32) -> Self::Output {
        let mut code = String::with_capacity(1024);

        // comment
        code.push_str("/////////////////////////////////////////////////////, ItemStr, default///////////////////////////////////////////////////////////////////");
        code.push_str(end);
        code.push_str("// This File is generated by the program, DO NOT EDIT MANUALLY!");
        code.push_str(end);
        code.push_str("// 此文件由程序生成, 切勿手动编辑!");
        code.push_str(end);
        code.push_str("////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////");
        code.push_str(end);

        // using
        code.push_str("using System;");
        code.push_str(end);
        code.push_str("using System.Linq;");
        code.push_str(end);
        code.push_str("using System.Collections;");
        code.push_str(end);
        code.push_str("using System.Collections.Generic;");
        code.push_str(end);
        code.push_str("using Config.Common;");
        code.push_str(end);
        code.push_str(end);

        // #pragma
        code.push_str("#pragma warning disable 1591");
        code.push_str(end);
        code.push_str(end);

        // namespace-start
        code.push_str("namespace Config");
        code.push_str(end);
        code.push('{');
        code.push_str(end);

        // ItemClass
        code.push_str(self.item_class.gen_code(end, tab_nums + 1).as_str());
        code.push_str(end);
        // BaseClass

        // namespace-end
        code.push('}');
        
        code
    }
}

impl Parser {
    pub fn new() -> Self {
        Parser { 
            item_class: ItemClass::default(),
            defaults: DefaultData::default(),
            key_type: KeyType::None,
        }
    }

    pub fn read_file(&mut self, file_name: &str) -> Result<()> {
        let file = ExcelFile::load_from_path(file_name);
        self.item_class.name = String::from(file_name);
        self.item_class.name.remove_matches(".xlsx");

        if let Ok(mut ff) = file {
            if let Ok(ret) = ff.parse_workbook() {
                for (name, id) in ret.into_iter() {
                    println!("{}, {}", name, id);

                    let content = ff.parse_sheet(*id);
                    if let Ok(table) = content {
                        if name == "Template" {
                            self.parse_template(table);
                        }
                    }
                }
            }
        } else if let Err(e) = file {
            return Err(Error::new(ErrorKind::Other, e));
        } else {
            return Err(Error::new(ErrorKind::Other, "load from xlsx file failed"));
        }

        Ok(())
    }

    pub fn generate(&self, end: &'static str) -> String {
        self.gen_code(end, 0)
    }

//------------------------private---------------------------------

    fn parse_template(&mut self, table: ExcelTable) {
        // check flag for (1, 3)
        if let Some(v) = table.cell(DATA_TEMPLATE_ID_POS.0, DATA_TEMPLATE_ID_POS.1) {
            println!("{}", v);
            if v.starts_with("#") {
                if v.contains("DefKey") {
                    self.key_type = KeyType::DefKey(vec![]);
                } else {
                    self.key_type = KeyType::OriginalTemplateId;
                }
            }
        }

        // collect (comment, identify, type) in row (1, 3, 4)
        match self.key_type {
            KeyType::DefKey(_) | KeyType::OriginalTemplateId => {
                for col in (0..table.width()).filter(|x| *x != DATA_TEMPLATE_ID_POS.0) {
                    if let (Some(c1), Some(c2), Some(c3)) = 
                        (table.cell(col, DATA_COMMENT_ROW), table.cell(col, DATA_IDENTIFY_ROW), table.cell(col, DATA_TYPE_ROW)) {
                        self.item_class.items.push(( Some(c1.clone()), Some(c2.clone()), Some(convert_type(c3.clone())) ));
                    }
                }
            },
            _ => {
                for col in 0..table.width() {
                    if let (Some(c1), Some(c2), Some(c3)) = 
                        (table.cell(col, DATA_COMMENT_ROW), table.cell(col, DATA_IDENTIFY_ROW), table.cell(col, DATA_TYPE_ROW)) {
                        self.item_class.items.push(( Some(c1.clone()), Some(c2.clone()), Some(convert_type(c3.clone())) ));
                    }
                }
            }
        };

        // collect DefKey in col 1, data start frow row 8
        if let KeyType::DefKey(ref mut vec) = self.key_type {
            for row in DATA_START_ROW..table.height() - 1 {
                if let Some(v) = table.cell(DATA_TEMPLATE_ID_POS.0, row) {
                    vec.push(Some(v.clone()));
                }
            }

            println!("{:?}", vec);
        }

    }

}

fn convert_type(mut v: Rc<String>) -> Rc<String> {
    if let Some(s) = Rc::get_mut(&mut v)
    {
        // convert string
        *s = s.replace("LString", "string");
        // convert array
        if let Some(idx) = s.find('[') {
            let mut n = idx;
            while let Some(c) = s.chars().nth(n) {
                if c == ']' {
                    break;
                } else {
                    n = n + 1;
                }
            }
            s.replace_range(idx+1..n, "");
        }
    }
    v
}